rvm:
  - ruby-head
  - jruby-head
  - jruby-19mode
  - 2.7
  - 2.6
  - 2.5
os:
  - linux
  - osx
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head

env: TEST=true
